from theanolm.filetypes import TextFileType
from wordclasses.theanobigramoptimizer import TheanoBigramOptimizer
from wordclasses.numpybigramoptimizer import NumpyBigramOptimizer
from wordclasses.wctool import main
